version: "3"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB:
  venv:
    build:
      context: ../
      dockerfile: Dockerfile.venv
    image: venv
    environment:
      - PYTHONPATH=/opt/src
    ports:
      - 4040:4040
      - 8888:8888
      - 8080:8080
    volumes:
       - ../src:/opt/src
       - ../data:/opt/data
       - ../configs:/opt/configs
       - ../src/core/airflow_dags:/root/airflow/dags
    stdin_open: true
    tty: true
