version: "3"
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: boilerplate_2023
      POSTGRES_USER: boilerplate_2023
      POSTGRES_DB: boilerplate_2023_db
