source: development-config

blob_storage_login:
    account_name: <dummy>
    account_key: <dummy>

sql_login:
    username: <dummy>
    password: <dummy>

sql_connection:
    driver_path: <dummy>
    server: localhost
    port: 5432
    db_name: <dummy>
