source: development-config

blob_storage_login:
    account_name: <dummy>
    account_key: <dummy>

sql_login:
    username: <put_username_here>
    password: <put_password_here>

sql_connection:
    driver_path: <dummy>
    server: localhost
    port: 5432
    db_name: boilerplate_db
